import Head from "next/head";
import { Inter } from "@next/font/google";
import Feature from "@/components/Feature";
import PizzaList from "@/components/PizzaList";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });

export default function Home({ pizzas }) {
  // console.log(pizzas);
  return (
    <div>
      <Head>
        <title>Pizza Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100">
        <Feature />
        <PizzaList pizzas={pizzas} />
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const pizzas = await axios
    .get(process.env.NEXT_URL + "/api/products")
    .then((res) => res.data);

  return {
    props: {
      pizzas,
    },
  };
}
